-- The schema Hibernate's ddl-auto=update had already produced before Flyway was introduced
-- (verified via pg_dump --schema-only against a real deployment of this app), reproduced here as
-- a real baseline migration.
--
-- This script only actually EXECUTES against a genuinely empty database (a fresh install, or a
-- fresh test/CI database) -- Flyway detects that case itself and runs it for real. Against any
-- database that already has this schema (every real pre-Flyway deployment), spring.flyway.baseline-on-migrate
-- marks this version as already-applied without running its body at all, so it's safe for this
-- script to fully recreate the schema without any IF NOT EXISTS/defensive guards: it only ever
-- runs once, against nothing.
--
-- All real schema changes start at V2.

CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    locked_until TIMESTAMP(6) WITH TIME ZONE,
    failed_login_attempts INTEGER NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    totp_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    totp_secret VARCHAR(255),
    activated BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT app_user_role_check CHECK (role IN ('ANALYST', 'ADMIN', 'CLIENT')),
    CONSTRAINT uk_app_user_username UNIQUE (username)
);

CREATE TABLE user_loan_id (
    user_id BIGINT NOT NULL REFERENCES app_user(id),
    loan_id VARCHAR(255),
    CONSTRAINT uk_user_loan_id UNIQUE (user_id, loan_id)
);

CREATE TABLE login_attempt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    success BOOLEAN NOT NULL,
    username VARCHAR(255) NOT NULL
);

CREATE TABLE loan_score (
    loan_id VARCHAR(255) NOT NULL PRIMARY KEY,
    calibrated_probability DOUBLE PRECISION NOT NULL,
    computed_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    raw_probability DOUBLE PRECISION NOT NULL
);

CREATE TABLE loan_case (
    loan_id VARCHAR(255) NOT NULL PRIMARY KEY,
    assigned_to VARCHAR(255),
    flagged BOOLEAN NOT NULL,
    status VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT loan_case_status_check CHECK (status IN ('NEW', 'REVIEWED', 'ESCALATED', 'CLEARED'))
);

CREATE TABLE loan_note (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    loan_id VARCHAR(255) NOT NULL,
    text VARCHAR(2000) NOT NULL
);

CREATE TABLE model_invocation_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint VARCHAR(255) NOT NULL,
    error_message TEXT,
    latency_ms BIGINT NOT NULL,
    occurred_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    request_json TEXT,
    response_json TEXT,
    success BOOLEAN NOT NULL
);
